server:
    port: 7070
    context-path: /uaa

spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/spring_cloud_security?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
        username: root
        password: root
        sql-script-encoding: UTF-8

mybatis:
    mapper-locations: classpath:config/mapper/**/*.xml
    type-aliases-package: com.utrons.**.model

security:
    oauth2:
        resource:
            filter-order: 3
logging:
    level:
      root: info